import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-gray-800 text-left p-8 text-white rounded-xl m-12 text-gray-100 text-xl">
        <h1 className="font-bold">Welcome to React, Elliott!</h1>
        <p>
          We're going to go through a few steps to get you set up with React.
        </p>
        <ul className="mt-4 pl-4">
          <li>
            1. Pull down this code:{" "}
            <span className="text-purple-500">
              git clone https://github.com/jonbell-lot23/amongus-elliott.git
            </span>
          </li>
          <li>
            2. Type <span className="text-purple-500">npm i</span> to install
            everything
          </li>
          <li>
            3. Type <span className="text-purple-500">npm run dev</span> to spin
            up the code on your computer{" "}
          </li>
          <li>
            4. Then visit{" "}
            <a className="text-purple-500" href="http://localhost:3000">
              localhost:3000
            </a>{" "}
            to take a look!
          </li>
        </ul>
        <p className="my-8">
          So now we know how to pull code down and run it locally. Pretty cool!
          Now let's walk through how to make changes and post them online!
        </p>
        <h1 className="font-bold">Woo!</h1>
        <ul className="mt-4 pl-4">
          <li>
            1. Go to pages/ and duplicate{" "}
            <span className="text-purple-500">index.js</span> to a new file
            called <span className="text-purple-500">backup.js</span>.
          </li>
          <li>2. Type something in index.js. Anything you want!</li>
          <li>
            3. Type <span className="text-purple-500">npm run deploy</span> to
            push the code onto the internet!
          </li>
          <li>
            4. Finally, type
            <span className="text-purple-500"> git commit -m "Updates"</span> to
            commit your changes and{" "}
            <span className="text-purple-500"> git push</span> to push it to
            GitHub.
          </li>
        </ul>
        <h1 className="font-bold mt-8">Let's gooooooooooo</h1>
        <div
          className="tenor-gif-embed"
          data-postid="8989586"
          data-share-method="host"
          data-aspect-ratio="1.77654"
          data-width="100%"
        >
          <a href="https://tenor.com/view/gokart-kid-spinning-fidget-fidgetspinner-gif-8989586">
            Gokart Kid GIF
          </a>
          from <a href="https://tenor.com/search/gokart-gifs">Gokart GIFs</a>
        </div>{" "}
        <script
          type="text/javascript"
          async
          src="https://tenor.com/embed.js"
        ></script>
      </div>
    </div>
  );
}
